[workspace]
members = ["viewer"]

[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools-num = "0.1.3"
num-traits = "0.2.17"
png = { git = "https://github.com/rrbutani/image-png" }
gif = "0.12.0"